import { join } from "node:path";
import type { GeneratedFile } from "./index";

export type TemplateSet = { [name: string]: string };

export const BUILTIN_GITHUB_TEMPLATES: TemplateSet = {
  "adapter/AGENTS.md": [
    "<!-- UT-TDD:managed:start -->",
    "# UT-TDD Agent Harness Adapter",
    "",
    "This project uses UT-TDD Agent Harness commands as the local orchestration surface.",
    "",
    "- Status: `ut-tdd status`",
    "- Doctor: `ut-tdd doctor`",
    "- Handover: `ut-tdd handover`",
    '- Codex delegation: `ut-tdd codex --role <role> --task "..."`',
    '- Claude delegation: `ut-tdd claude --role <role> --task "..."`',
    "- Team run: `ut-tdd team run --definition .ut-tdd/teams/<team>.yaml`",
    "",
    "Project-owned instructions outside this managed block remain consumer-owned.",
    "<!-- UT-TDD:managed:end -->",
    "",
  ].join("\n"),
  "adapter/CLAUDE.md": [
    "<!-- UT-TDD:managed:start -->",
    "# UT-TDD Agent Harness Shared Context",
    "",
    "Use repository-local UT-TDD commands for harness state and delegation.",
    "",
    "- `ut-tdd status` reports the local runtime mode.",
    "- `ut-tdd doctor` runs repository health checks.",
    "- `ut-tdd handover` reads and writes cross-runtime handover state.",
    '- `ut-tdd codex --role <role> --task "..."` delegates to Codex.',
    '- `ut-tdd claude --role <role> --task "..."` delegates to Claude.',
    "",
    "Do not put secrets, tokens, or machine-local absolute paths in adapter docs.",
    "<!-- UT-TDD:managed:end -->",
    "",
  ].join("\n"),
  "adapter/.claude/CLAUDE.md": [
    "<!-- UT-TDD:managed:start -->",
    "# Claude Runtime Adapter",
    "",
    "Claude Code sessions should route harness lifecycle work through `ut-tdd`.",
    "Consumer-owned Claude instructions can be added outside this managed block.",
    "",
    "- Session evidence: `ut-tdd status` and `ut-tdd handover`",
    "- Health check: `ut-tdd doctor`",
    "- Review separation: use another runtime/model family when feasible",
    "",
    "<!-- UT-TDD:managed:end -->",
    "",
  ].join("\n"),
  "adapter/.claude/settings.json": [
    "{",
    '  "hooks": {',
    '    "SessionStart": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd session start",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: session start (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "PostToolUse": [',
    "      {",
    '        "matcher": "Edit|Write|MultiEdit|Bash",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd hook post-tool-use",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: post tool use (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "Stop": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "ut-tdd session summary",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: PLAN digest summary (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ]",
    "  }",
    "}",
    "",
  ].join("\n"),
  "common/harness-check.yml": [
    "name: harness-check",
    "on:",
    "  push:",
    "    branches: [main]",
    "  pull_request:",
    "    branches: [main]",
    "jobs:",
    "  harness-check:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "      - uses: oven-sh/setup-bun@v2",
    "      - run: bun install --frozen-lockfile",
    "      - run: bun run typecheck",
    "      - run: bun run test",
    "",
  ].join("\n"),
  "common/commitlint.config.js":
    "module.exports = { extends: ['@commitlint/config-conventional'] };\n",
  "common/escalation-stale.yml": [
    "name: escalation-stale",
    "on:",
    "  schedule:",
    "    - cron: '0 0 * * 1'",
    "jobs:",
    "  noop:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - run: echo escalation policy placeholder",
    "",
  ].join("\n"),
  "common/recovery.md":
    "# Recovery\n\nDescribe the broken invariant, evidence, and rollback path.\n",
  "common/add-feature.md":
    "# Add Feature\n\nDescribe objective, scope, tests, and review evidence.\n",
  "common/PULL_REQUEST_TEMPLATE.md":
    "## Summary\n\n## Verification\n\n## Review evidence\n\nCloses #\n",
  "team/CODEOWNERS": [
    "* {{TL_TEAM}}",
    "/docs/ {{PO_TEAM}}",
    "/src/ {{TL_TEAM}}",
    "/tests/ {{QA_TEAM}}",
    "",
  ].join("\n"),
  "team/setup-branch-protection.sh": [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    'REPO="$' + '{1:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"',
    'echo "Apply branch protection to $' + '{REPO}/main"',
    'read -r -p "Continue? [y/N] " ans',
    '[[ "$' + '{ans}" == "y" || "$' + '{ans}" == "Y" ]] || exit 1',
    'gh api -X PUT "repos/$' + '{REPO}/branches/main/protection" \\',
    '  -H "Accept: application/vnd.github+json" \\',
    "  --input - <<'JSON'",
    "{",
    '  "required_status_checks": { "strict": true, "checks": [ { "context": "harness-check" } ] },',
    '  "enforce_admins": true,',
    '  "required_pull_request_reviews": { "required_approving_review_count": 1 },',
    '  "restrictions": null',
    "}",
    "JSON",
    "",
  ].join("\n"),
};

export const COMMON_FILES: { template: string; file: GeneratedFile }[] = [
  {
    template: "adapter/AGENTS.md",
    file: {
      path: "AGENTS.md",
      category: "A",
      purpose: "UT-TDD adapter instructions (managed block)",
    },
  },
  {
    template: "adapter/CLAUDE.md",
    file: {
      path: "CLAUDE.md",
      category: "A",
      purpose: "UT-TDD shared adapter context (managed block)",
    },
  },
  {
    template: "adapter/.claude/CLAUDE.md",
    file: {
      path: join(".claude", "CLAUDE.md"),
      category: "A",
      purpose: "Claude runtime adapter instructions (managed block)",
    },
  },
  {
    template: "adapter/.claude/settings.json",
    file: {
      path: join(".claude", "settings.json"),
      category: "A",
      purpose: "Claude hook settings for UT-TDD CLI entrypoints",
    },
  },
  {
    template: "common/harness-check.yml",
    file: {
      path: join(".github", "workflows", "harness-check.yml"),
      category: "A",
      purpose: "CI (typecheck + regression)",
    },
  },
  {
    template: "common/commitlint.config.js",
    file: { path: "commitlint.config.js", category: "A", purpose: "Conventional Commits" },
  },
  {
    template: "common/escalation-stale.yml",
    file: {
      path: join(".github", "workflows", "escalation-stale.yml"),
      category: "A",
      purpose: "stale escalation issue workflow",
    },
  },
  {
    template: "common/recovery.md",
    file: {
      path: join(".github", "ISSUE_TEMPLATE", "recovery.md"),
      category: "A",
      purpose: "Recovery issue template",
    },
  },
  {
    template: "common/add-feature.md",
    file: {
      path: join(".github", "ISSUE_TEMPLATE", "add-feature.md"),
      category: "A",
      purpose: "Add-feature issue template",
    },
  },
  {
    template: "common/PULL_REQUEST_TEMPLATE.md",
    file: {
      path: join(".github", "PULL_REQUEST_TEMPLATE.md"),
      category: "A",
      purpose: "PR template",
    },
  },
];
