import type { TableDef } from "./harness-db";
import { col, pk } from "./harness-db-table-builders";

export const HARNESS_DB_SPEC_IR_TABLES: TableDef[] = [
  {
    name: "spec_defs",
    columns: [
      pk("spec_id"),
      col("spec_kind"),
      col("layer"),
      col("sub_doc"),
      col("owner_artifact_id"),
      col("owner_path"),
      col("section_anchor"),
      col("title"),
      col("lifecycle_status"),
      col("plan_id"),
      col("source_path"),
      col("source_hash"),
      col("indexed_at"),
    ],
  },
  {
    name: "spec_relations",
    columns: [
      pk("relation_id"),
      col("from_spec_id"),
      col("to_spec_id"),
      col("relation_kind"),
      col("plan_id"),
      col("status"),
      col("source"),
      col("evidence_path"),
      col("indexed_at"),
    ],
  },
  {
    name: "schedule_entries",
    columns: [
      pk("schedule_entry_id"),
      col("plan_id"),
      col("layer"),
      col("sub_doc"),
      col("v_pair"),
      col("predecessor_plan_ids"),
      col("current_location"),
      col("rag"),
      col("status"),
      col("blocked_reason"),
      col("source_path"),
      col("source_hash"),
      col("indexed_at"),
    ],
  },
  {
    name: "activation_entries",
    columns: [
      pk("activation_entry_id"),
      col("profile_id"),
      col("target_kind"),
      col("target_id"),
      col("scope_status"),
      col("target_version"),
      col("defer_reason"),
      col("enabled", "INTEGER"),
      col("source_path"),
      col("plan_id"),
      col("indexed_at"),
    ],
  },
  {
    name: "detector_route_candidates",
    columns: [
      pk("route_candidate_id"),
      col("source_table"),
      col("source_id"),
      col("detector_id"),
      col("finding_kind"),
      col("severity"),
      col("subject_kind"),
      col("subject_id"),
      col("filing_target_id"),
      col("target_layer"),
      col("target_sub_doc"),
      col("candidate_status"),
      col("reason"),
      col("evidence_path"),
      col("computed_at"),
    ],
  },
];
